/*******************************************************************************
* File Name: DigitalComp_v1_0.v
* Version `$CY_MAJOR_VERSION`.`$CY_MINOR_VERSION`
*
* Description:
* The Digital Comparator component provides a selectable-width, selectable-type
* comparator, implemented in PLD macrocells. The verilog is generated by the
* CustomizeVerilog method in the CyCustomizer class in custom.cs.
*
********************************************************************************
* I*O Signals:
********************************************************************************
*   Name        Direction       Description
*   cmp         output          Result of comparison
*   a           input           First operand of comparison
*   b           input           Second operand of comparison
*
********************************************************************************
* Copyright 2012, Cypress Semiconductor Corporation. All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/
