//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMA_Channel_P4_v1_0 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMA_Channel_P4_v1_0.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        internal static string BuiltInTabName {
            get {
                return ResourceManager.GetString("BuiltInTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte to Byte.
        /// </summary>
        internal static string ByteToByte {
            get {
                return ResourceManager.GetString("ByteToByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte to Word.
        /// </summary>
        internal static string ByteToWord {
            get {
                return ResourceManager.GetString("ByteToWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain to descriptor 1 is not available when number of descriptors is 1.
        /// </summary>
        internal static string ChainToDescripto1Error {
            get {
                return ResourceManager.GetString("ChainToDescripto1Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain to descriptor {0}.
        /// </summary>
        internal static string ChainToDescriptor {
            get {
                return ResourceManager.GetString("ChainToDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string ChannelTabName {
            get {
                return ResourceManager.GetString("ChannelTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptor 0.
        /// </summary>
        internal static string Descriptor0TabName {
            get {
                return ResourceManager.GetString("Descriptor0TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptor 1.
        /// </summary>
        internal static string Descriptor1TabName {
            get {
                return ResourceManager.GetString("Descriptor1TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptor {0} is preemptable.
        /// </summary>
        internal static string DescriptorIsPreemptable {
            get {
                return ResourceManager.GetString("DescriptorIsPreemptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire descriptor chain per trigger is not available when number of descriptors is 1.
        /// </summary>
        internal static string EntireDescriptorChainError {
            get {
                return ResourceManager.GetString("EntireDescriptorChainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ErrorClear {
            get {
                return ResourceManager.GetString("ErrorClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halfword to Halfword.
        /// </summary>
        internal static string HalfwordToHalfword {
            get {
                return ResourceManager.GetString("HalfwordToHalfword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halfword to Word.
        /// </summary>
        internal static string HalfwordToWord {
            get {
                return ResourceManager.GetString("HalfwordToWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgByte {
            get {
                object obj = ResourceManager.GetObject("imgByte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgHalfword {
            get {
                object obj = ResourceManager.GetObject("imgHalfword", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgWord {
            get {
                object obj = ResourceManager.GetObject("imgWord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment destination address by four.
        /// </summary>
        internal static string IncDstByFour {
            get {
                return ResourceManager.GetString("IncDstByFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment destination address by one.
        /// </summary>
        internal static string IncDstByOne {
            get {
                return ResourceManager.GetString("IncDstByOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment destination address by two.
        /// </summary>
        internal static string IncDstByTwo {
            get {
                return ResourceManager.GetString("IncDstByTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment source address by four.
        /// </summary>
        internal static string IncSrcByFour {
            get {
                return ResourceManager.GetString("IncSrcByFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment source address by one.
        /// </summary>
        internal static string IncSrcByOne {
            get {
                return ResourceManager.GetString("IncSrcByOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment source address by two.
        /// </summary>
        internal static string IncSrcByTwo {
            get {
                return ResourceManager.GetString("IncSrcByTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidate descriptor {0}.
        /// </summary>
        internal static string InvalidateDescriptor {
            get {
                return ResourceManager.GetString("InvalidateDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of data elements must be set between 1 and 65536..
        /// </summary>
        internal static string NumOfDataElementError {
            get {
                return ResourceManager.GetString("NumOfDataElementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word to Byte.
        /// </summary>
        internal static string WordToByte {
            get {
                return ResourceManager.GetString("WordToByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word to Halfword.
        /// </summary>
        internal static string WordToHalfword {
            get {
                return ResourceManager.GetString("WordToHalfword", resourceCulture);
            }
        }
    }
}
