/*******************************************************************************
* File Name: cy_dffe_v1_0.v
* Version `$CY_MAJOR_VERSION`.`$CY_MINOR_VERSION`
*
* Description:
* The D Flip Flop w/ Enable component selectively stores a digital value. The
* verilog is generated by the CustomizeVerilog method in the CyCustomizer class
* in custom.cs.
*
********************************************************************************
* I*O Signals:
********************************************************************************
*   Name        Direction       Description
*   q           output          Stored value.
*   clk         input           When output may change.
*   d           input           Next value of output.
*   en          input           Whether to store value.
*
********************************************************************************
* Copyright 2012, Cypress Semiconductor Corporation. All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/
