//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerMonitor_P4_v2_0 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerMonitor_P4_v2_0.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The design was changed after the component was configured, resulting in a component clock that is too fast. Please open the component GUI and click &apos;Okay&apos;. This will allow the component to choose a valid clock..
        /// </summary>
        public static string AdcClockDividerError {
            get {
                return ResourceManager.GetString("AdcClockDividerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The design was changed  after the component was configured, resulting in a clock that is suboptimal.  Please open the component GUI and click &apos;Okay&apos;. This will allow the component to choose the optimal clock..
        /// </summary>
        public static string AdcClockDividerOptimization {
            get {
                return ResourceManager.GetString("AdcClockDividerOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADC range cannot be Differential when voltage measurement type is Single Ended..
        /// </summary>
        public static string AdcRangeDifferentialInvalid {
            get {
                return ResourceManager.GetString("AdcRangeDifferentialInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADC range cannot be Single Ended when voltage measurement type is Differential..
        /// </summary>
        public static string AdcRangeSingleEndedInvalid {
            get {
                return ResourceManager.GetString("AdcRangeSingleEndedInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary Voltages.
        /// </summary>
        public static string AuxTabDisplayName {
            get {
                return ResourceManager.GetString("AuxTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string BasicTabDisplayName {
            get {
                return ResourceManager.GetString("BasicTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        public static string BuiltInTabDisplayName {
            get {
                return ResourceManager.GetString("BuiltInTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t resolve type..
        /// </summary>
        public static string CannotResolveType {
            get {
                return ResourceManager.GetString("CannotResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSA gain value must be between {0} and {1}..
        /// </summary>
        public static string CsaGainError {
            get {
                return ResourceManager.GetString("CsaGainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Converter Currents.
        /// </summary>
        public static string CurrentsTabDisplayName {
            get {
                return ResourceManager.GetString("CurrentsTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power converter currents table contains empty rows. Please initialize empty rows or decrease number of converters..
        /// </summary>
        public static string CurrentsTableEmptyRowsDRC {
            get {
                return ResourceManager.GetString("CurrentsTableEmptyRowsDRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition time must be between {0} and {1} ns..
        /// </summary>
        public static string errAcquisitionTime {
            get {
                return ResourceManager.GetString("errAcquisitionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vref value must be between {0} V and {1} V..
        /// </summary>
        public static string ErrorVrefValueBounds {
            get {
                return ResourceManager.GetString("ErrorVrefValueBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All.
        /// </summary>
        public static string ExportAllTitle {
            get {
                return ResourceManager.GetString("ExportAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to File.
        /// </summary>
        public static string ExportToFileTitle {
            get {
                return ResourceManager.GetString("ExportToFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with this name already exists. Do you want to replace it?.
        /// </summary>
        public static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Import {
            get {
                object obj = ResourceManager.GetObject("Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import All.
        /// </summary>
        public static string ImportAllTitle {
            get {
                return ResourceManager.GetString("ImportAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data in the grid will be lost after import. Would you like to continue?.
        /// </summary>
        public static string ImportConfirmation {
            get {
                return ResourceManager.GetString("ImportConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from File.
        /// </summary>
        public static string ImportFromFileTitle {
            get {
                return ResourceManager.GetString("ImportFromFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input voltage scaling factor must be between {0} and {1}..
        /// </summary>
        public static string InputScalingFactorError {
            get {
                return ResourceManager.GetString("InputScalingFactorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input scaling factor must be equal to 1 when current measurement type is Direct..
        /// </summary>
        public static string InputScalingFactorNotEqualOne {
            get {
                return ResourceManager.GetString("InputScalingFactorNotEqualOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert data into table. Data format is not valid..
        /// </summary>
        public static string InvalidDataFormat {
            get {
                return ResourceManager.GetString("InvalidDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the configuration..
        /// </summary>
        public static string LoadCondigErrorMsg {
            get {
                return ResourceManager.GetString("LoadCondigErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during loading configuration parameters..
        /// </summary>
        public static string LoadCondigParamsErrorMsg {
            get {
                return ResourceManager.GetString("LoadCondigParamsErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data in the customizer will be lost after import. Would you like to continue?.
        /// </summary>
        public static string LoadConfirmation {
            get {
                return ResourceManager.GetString("LoadConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from File.
        /// </summary>
        public static string LoadDialogHeader {
            get {
                return ResourceManager.GetString("LoadDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal output voltage value must be between {0} V and {1} V..
        /// </summary>
        public static string NominalOutputVoltageError {
            get {
                return ResourceManager.GetString("NominalOutputVoltageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of auxiliary channels cannot be more than {0}..
        /// </summary>
        public static string NumAuxChannelsError {
            get {
                return ResourceManager.GetString("NumAuxChannelsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of converters must be between {0} and {1}..
        /// </summary>
        public static string NumConvertersError {
            get {
                return ResourceManager.GetString("NumConvertersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product of OC threshold value, shunt resistance and CSA gain should be less than ADC range for CSA current which is {0:0.###}V..
        /// </summary>
        public static string OcFaultThresholdCSASanityCheck {
            get {
                return ResourceManager.GetString("OcFaultThresholdCSASanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OC fault threshold value must be between {0} A and {1} A..
        /// </summary>
        public static string OcFaultThresholdError {
            get {
                return ResourceManager.GetString("OcFaultThresholdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OC fault threshold value multiplied by shunt resistor value must be less than or equal to {0}..
        /// </summary>
        public static string OcFaultThresholdSanityCheck {
            get {
                return ResourceManager.GetString("OcFaultThresholdSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OC warning threshold value must be between {0} A and {1} A..
        /// </summary>
        public static string OcWarningThresholdError {
            get {
                return ResourceManager.GetString("OcWarningThresholdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OC warning threshold must be less than or equal to OC fault threshold..
        /// </summary>
        public static string OcWarningThresholdSanityCheck {
            get {
                return ResourceManager.GetString("OcWarningThresholdSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OV fault threshold value multiplied by scale must be less than or equal to {0} V..
        /// </summary>
        public static string OvFaultMultScaleSanityCheck {
            get {
                return ResourceManager.GetString("OvFaultMultScaleSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OV fault threshold value must be greater than or equal to OV warning threshold..
        /// </summary>
        public static string OvFaultSanityCheck {
            get {
                return ResourceManager.GetString("OvFaultSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OV fault threshold value must be between {0} V and {1} V..
        /// </summary>
        public static string OvFaultthresholdError {
            get {
                return ResourceManager.GetString("OvFaultthresholdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OV warning threshold value must be greater than or equal to nominal output voltage..
        /// </summary>
        public static string OvWarningSanityCheck {
            get {
                return ResourceManager.GetString("OvWarningSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OV warning threshold value must be between {0} V and {1} V..
        /// </summary>
        public static string OvWarningthresholdError {
            get {
                return ResourceManager.GetString("OvWarningthresholdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (pgood becomes a single terminal).
        /// </summary>
        public static string PgoodGlobalDesc {
            get {
                return ResourceManager.GetString("PgoodGlobalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (pgood becomes a bus).
        /// </summary>
        public static string PgoodIndividualDesc {
            get {
                return ResourceManager.GetString("PgoodIndividualDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total number of analog inputs is limited to 48 (in any combination of vx, ix and rtnx). Reduce the number of analog inputs in the component configuration dialog.  For more information refer to the component datasheet..
        /// </summary>
        public static string PinsCountLimitation {
            get {
                return ResourceManager.GetString("PinsCountLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to File.
        /// </summary>
        public static string SaveDialogHeader {
            get {
                return ResourceManager.GetString("SaveDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have incorrect values! You must redefine them..
        /// </summary>
        public static string SettingsIncorrectValues {
            get {
                return ResourceManager.GetString("SettingsIncorrectValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shunt resistor value must be between {0} mΩ and {1} mΩ..
        /// </summary>
        public static string ShuntResistorError {
            get {
                return ResourceManager.GetString("ShuntResistorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV fault threshold value multiplied by scale must be greater than or equal to {0}..
        /// </summary>
        public static string UvFaultMultScaleSanityCheck {
            get {
                return ResourceManager.GetString("UvFaultMultScaleSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV fault threshold value must be less or equal to UV warning threshold..
        /// </summary>
        public static string UvFaultSanityCheck {
            get {
                return ResourceManager.GetString("UvFaultSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV fault threshold value must be between {0} V and {1} V..
        /// </summary>
        public static string UvFaultthresholdError {
            get {
                return ResourceManager.GetString("UvFaultthresholdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV warning threshold value must be less than or equal to nominal output voltage..
        /// </summary>
        public static string UvWarningSanityCheck {
            get {
                return ResourceManager.GetString("UvWarningSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV warning threshold value must be between {0} V and {1} V..
        /// </summary>
        public static string UvWarningthresholdError {
            get {
                return ResourceManager.GetString("UvWarningthresholdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Converter Voltages.
        /// </summary>
        public static string VoltagesTabDisplayName {
            get {
                return ResourceManager.GetString("VoltagesTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power converter voltages table contains empty rows. Please initialize empty rows or decrease number of converters..
        /// </summary>
        public static string VoltagesTableEmptyRowsDRC {
            get {
                return ResourceManager.GetString("VoltagesTableEmptyRowsDRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected type of voltage reference is not supported for the current device type..
        /// </summary>
        public static string VrefSelectPartError {
            get {
                return ResourceManager.GetString("VrefSelectPartError", resourceCulture);
            }
        }
    }
}
