//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveDAC8_v2_10 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class cywavedacresource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cywavedacresource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaveDAC8_v2_10.cywavedacresource", typeof(cywavedacresource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude ({0}):.
        /// </summary>
        internal static string AmplitudeLabelText {
            get {
                return ResourceManager.GetString("AmplitudeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        internal static string BuiltinTabDisplayName {
            get {
                return ResourceManager.GetString("BuiltinTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock frequency for  selected DAC range must be between {0} and {1} kHz..
        /// </summary>
        internal static string ClockFrequencyError {
            get {
                return ResourceManager.GetString("ClockFrequencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Waveform.
        /// </summary>
        internal static string DialogImportTitle {
            get {
                return ResourceManager.GetString("DialogImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field cannot be empty.
        /// </summary>
        internal static string ErrorEmptyField {
            get {
                return ResourceManager.GetString("ErrorEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect value.
        /// </summary>
        internal static string ErrorIncorrectValue {
            get {
                return ResourceManager.GetString("ErrorIncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File contains incorrect data. Number of samples must be between {0} and {1}.
        /// </summary>
        internal static string ErrorNumOfSamples {
            get {
                return ResourceManager.GetString("ErrorNumOfSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File contains incorrect data. The file must contain a series of values, each in the range of 0 to 255..
        /// </summary>
        internal static string ErrorParseDataValue {
            get {
                return ResourceManager.GetString("ErrorParseDataValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file {0}..
        /// </summary>
        internal static string FileReadError {
            get {
                return ResourceManager.GetString("FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralTabDisplayName {
            get {
                return ResourceManager.GetString("GeneralTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waveform .
        /// </summary>
        internal static string GroupBoxWaveformTitle {
            get {
                return ResourceManager.GetString("GroupBoxWaveformTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency: {0}.
        /// </summary>
        internal static string LabelChartFrequency {
            get {
                return ResourceManager.GetString("LabelChartFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period: {0}.
        /// </summary>
        internal static string LabelChartPeriod {
            get {
                return ResourceManager.GetString("LabelChartPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MsgErrorTitle {
            get {
                return ResourceManager.GetString("MsgErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between {0} and {1}.
        /// </summary>
        internal static string MsgOutOfRange {
            get {
                return ResourceManager.GetString("MsgOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MsgWarningTitle {
            get {
                return ResourceManager.GetString("MsgWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset ({0}):.
        /// </summary>
        internal static string OffsetLabelText {
            get {
                return ResourceManager.GetString("OffsetLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UnknownStr {
            get {
                return ResourceManager.GetString("UnknownStr", resourceCulture);
            }
        }
    }
}
