//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyCustomizer.CyControlReg_v1_80 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CyCustomizer.CyControlReg_v1_80.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit.
        /// </summary>
        internal static string BIT {
            get {
                return ResourceManager.GetString("BIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitValue.
        /// </summary>
        internal static string BITVALUE {
            get {
                return ResourceManager.GetString("BITVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMode.
        /// </summary>
        internal static string DIRECTMODE {
            get {
                return ResourceManager.GetString("DIRECTMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string FALSE {
            get {
                return ResourceManager.GetString("FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string MODE {
            get {
                return ResourceManager.GetString("MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PulseMode.
        /// </summary>
        internal static string PULSEMODE {
            get {
                return ResourceManager.GetString("PULSEMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncMode.
        /// </summary>
        internal static string SYNCMODE {
            get {
                return ResourceManager.GetString("SYNCMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string TRUE {
            get {
                return ResourceManager.GetString("TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRC Check: Pulse output mode is not valid for PSoC5X silicon..
        /// </summary>
        internal static string VerifyBitFieldParamErrorMsg {
            get {
                return ResourceManager.GetString("VerifyBitFieldParamErrorMsg", resourceCulture);
            }
        }
    }
}
