//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cypress.Comps.PinsAndPorts.GPIO_PDL_v1_0 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cypress.Comps.PinsAndPorts.GPIO_PDL_v1_0.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [All pins].
        /// </summary>
        internal static string AllPins {
            get {
                return ResourceManager.GetString("AllPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AnalogEMF {
            get {
                object obj = ResourceManager.GetObject("AnalogEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ann1DownLeftEMF {
            get {
                object obj = ResourceManager.GetObject("Ann1DownLeftEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ann1DownRightEMF {
            get {
                object obj = ResourceManager.GetObject("Ann1DownRightEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ann2DownLeftEMF {
            get {
                object obj = ResourceManager.GetObject("Ann2DownLeftEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AnnLeftEMF {
            get {
                object obj = ResourceManager.GetObject("AnnLeftEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AnnRightEMF {
            get {
                object obj = ResourceManager.GetObject("AnnRightEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Assignment is unlocked and may be moved by the fitter when rebuilt..
        /// </summary>
        internal static string AssignmentUnlockedAnd {
            get {
                return ResourceManager.GetString("AssignmentUnlockedAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BidirEMF {
            get {
                object obj = ResourceManager.GetObject("BidirEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both edges.
        /// </summary>
        internal static string BothEdges {
            get {
                return ResourceManager.GetString("BothEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        internal static string BuiltIn {
            get {
                return ResourceManager.GetString("BuiltIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Selected Pin&apos;s Alias... (F2).
        /// </summary>
        internal static string Cmd_ChangeAlias {
            get {
                return ResourceManager.GetString("Cmd_ChangeAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Pin/s (Delete).
        /// </summary>
        internal static string Cmd_DeletePin {
            get {
                return ResourceManager.GetString("Cmd_DeletePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Selected Pin/s Down.
        /// </summary>
        internal static string Cmd_MovePinDown {
            get {
                return ResourceManager.GetString("Cmd_MovePinDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Selected Pin/s Up.
        /// </summary>
        internal static string Cmd_MovePinUp {
            get {
                return ResourceManager.GetString("Cmd_MovePinUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair Selected SIOs.
        /// </summary>
        internal static string Cmd_PairSelectedSIOs {
            get {
                return ResourceManager.GetString("Cmd_PairSelectedSIOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-pair Selected SIOs.
        /// </summary>
        internal static string Cmd_UnpairSelectedSIOs {
            get {
                return ResourceManager.GetString("Cmd_UnpairSelectedSIOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMOS.
        /// </summary>
        internal static string CMOS {
            get {
                return ResourceManager.GetString("CMOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMOS or LVTTL.
        /// </summary>
        internal static string CMOS_LVTTL {
            get {
                return ResourceManager.GetString("CMOS_LVTTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DefaultDriveModesEMF {
            get {
                object obj = ResourceManager.GetObject("DefaultDriveModesEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteImage {
            get {
                object obj = ResourceManager.GetObject("DeleteImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DigInAnalogEMF {
            get {
                object obj = ResourceManager.GetObject("DigInAnalogEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DigInEMF {
            get {
                object obj = ResourceManager.GetObject("DigInEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DigInNCAnalogEMF {
            get {
                object obj = ResourceManager.GetObject("DigInNCAnalogEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DigInNCEMF {
            get {
                object obj = ResourceManager.GetObject("DigInNCEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DigOutEMF {
            get {
                object obj = ResourceManager.GetObject("DigOutEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DigOutNCEMF {
            get {
                object obj = ResourceManager.GetObject("DigOutNCEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DigOutNCOEEMF {
            get {
                object obj = ResourceManager.GetObject("DigOutNCOEEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DigOutOEEMF {
            get {
                object obj = ResourceManager.GetObject("DigOutOEEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display as bus.
        /// </summary>
        internal static string DisplayAsBus {
            get {
                return ResourceManager.GetString("DisplayAsBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eighth.
        /// </summary>
        internal static string Eighth {
            get {
                return ResourceManager.GetString("Eighth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: Cannot uncheck all types..
        /// </summary>
        internal static string Err_CannotUncheckAllTypes {
            get {
                return ResourceManager.GetString("Err_CannotUncheckAllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: SIO features have been used by this pin therefore analog cannot be used. (SIO features include: HotSwap set to true, ThresholdLevels set to anything but LVTTL or CMOS, OutputDriveLevel set to Vref, and/or OutputCurrent set to a 40mA sink).
        /// </summary>
        internal static string Err_CannotUseAnalogAndSIO {
            get {
                return ResourceManager.GetString("Err_CannotUseAnalogAndSIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Adapter features have been used by this pin but the selected device does not have a Port Adapter. (Port Adapter features include: InputMode set to SingleSync or DoubleSync.).
        /// </summary>
        internal static string Err_CannotUsePAonDevice {
            get {
                return ResourceManager.GetString("Err_CannotUsePAonDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: This option requires a pin with the {1} feature but the selected device does not support {1}..
        /// </summary>
        internal static string Err_CannotUsePinTypeonDevice {
            get {
                return ResourceManager.GetString("Err_CannotUsePinTypeonDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component must be homogeneous to be displayed as a bus. This means that all pins in the component have the same pin type, input HW connections, output HW connections, SIO grouping, and either all use or don&apos;t use the SIO Vref.
        /// </summary>
        internal static string Err_DisplayAsBusRequiresHomogenous {
            get {
                return ResourceManager.GetString("Err_DisplayAsBusRequiresHomogenous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: Use of drive modes which are not High Impedance with a hardware-routed input requires a port adapter, but the selected device does not have one..
        /// </summary>
        internal static string Err_DriveModeRequiresPA {
            get {
                return ResourceManager.GetString("Err_DriveModeRequiresPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: Input Sync mode of &apos;{1}&apos; is not available for this device..
        /// </summary>
        internal static string Err_InputSyncInvalid {
            get {
                return ResourceManager.GetString("Err_InputSyncInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: The multiplier output must be less than VDDIO - 400 mV. Please adjust the multiplier or increase the minimum supply voltage..
        /// </summary>
        internal static string Err_M0S8_MultiplierOutputTooHigh {
            get {
                return ResourceManager.GetString("Err_M0S8_MultiplierOutputTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: When a pin is both an input and an output, the multiplier values for input threshold and drive level must match..
        /// </summary>
        internal static string Err_M0S8_MultipliersMustMatch {
            get {
                return ResourceManager.GetString("Err_M0S8_MultipliersMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: When SIOs are paired and use a Vref multiplier, the multiplier values must match..
        /// </summary>
        internal static string Err_M0S8_SioPairMultipliersMustMatch {
            get {
                return ResourceManager.GetString("Err_M0S8_SioPairMultipliersMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: When both SIOs in a pair use Vref, the Vref sources must match..
        /// </summary>
        internal static string Err_M0S8_SioPairRefSelMustMatch {
            get {
                return ResourceManager.GetString("Err_M0S8_SioPairRefSelMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: When both the input threshold and output drive level use Vref, the Vref sources must match..
        /// </summary>
        internal static string Err_M0S8_SioRefSelMustMatch {
            get {
                return ResourceManager.GetString("Err_M0S8_SioRefSelMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: When the drive level is set to internal Vref, the minimum supply voltage must be specified..
        /// </summary>
        internal static string Err_M0S8_VrefDriveLevelRequiresMinimumSupply {
            get {
                return ResourceManager.GetString("Err_M0S8_VrefDriveLevelRequiresMinimumSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: When the input threshold is set to internal Vref, the minimum supply voltage must be specified..
        /// </summary>
        internal static string Err_M0S8_VrefThresholdRequiresMinimumSupply {
            get {
                return ResourceManager.GetString("Err_M0S8_VrefThresholdRequiresMinimumSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: &apos;{1}&apos; is not a valid alias. An alias must be a valid C/C++ identifier name. {2}.
        /// </summary>
        internal static string Err_NotValidCIdentifier {
            get {
                return ResourceManager.GetString("Err_NotValidCIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: Output Sync mode of &apos;{1}&apos; is not available for this device..
        /// </summary>
        internal static string Err_OutputSyncInvalid {
            get {
                return ResourceManager.GetString("Err_OutputSyncInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: This selection is restricted to {1} pins, but the selection for {2} is restricted to {3} pins..
        /// </summary>
        internal static string Err_OvtAndSioFeaturesUsed {
            get {
                return ResourceManager.GetString("Err_OvtAndSioFeaturesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected device does not support output drive level of Vref if drive mode is set to Resistive Pull Up/Down..
        /// </summary>
        internal static string Err_P35_ResistivePullAndVrefOut {
            get {
                return ResourceManager.GetString("Err_P35_ResistivePullAndVrefOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumPins Validation Failed. The width must be between 1 and {0}..
        /// </summary>
        internal static string Err_PinCountOutOfRange {
            get {
                return ResourceManager.GetString("Err_PinCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: When SIOs are paired their Input Thresholds must match..
        /// </summary>
        internal static string Err_SIOPairInputsDontMatch {
            get {
                return ResourceManager.GetString("Err_SIOPairInputsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin {0}: When SIOs are paired their Output Drive Levels must match..
        /// </summary>
        internal static string Err_SIOPairOutputsDontMatch {
            get {
                return ResourceManager.GetString("Err_SIOPairOutputsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of pins must be less than or equal to 8 when interrupts are used in order for them all to fit within a single physical port..
        /// </summary>
        internal static string Err_TooManyPinsForInterrupt {
            get {
                return ResourceManager.GetString("Err_TooManyPinsForInterrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorImage {
            get {
                object obj = ResourceManager.GetObject("ErrorImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falling edge.
        /// </summary>
        internal static string FallingEdge {
            get {
                return ResourceManager.GetString("FallingEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string Fast {
            get {
                return ResourceManager.GetString("Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half.
        /// </summary>
        internal static string Half {
            get {
                return ResourceManager.GetString("Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5 x Vref.
        /// </summary>
        internal static string HalfVref {
            get {
                return ResourceManager.GetString("HalfVref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5 x Vref (Internal).
        /// </summary>
        internal static string HalfVrefInternal {
            get {
                return ResourceManager.GetString("HalfVrefInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Impedance Analog.
        /// </summary>
        internal static string HighImpedanceAnalog {
            get {
                return ResourceManager.GetString("HighImpedanceAnalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Impedance Digital.
        /// </summary>
        internal static string HighImpedanceDigital {
            get {
                return ResourceManager.GetString("HighImpedanceDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HiImpedanceAnalogEMF {
            get {
                object obj = ResourceManager.GetObject("HiImpedanceAnalogEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HiImpedanceDigitalEMF {
            get {
                object obj = ResourceManager.GetObject("HiImpedanceDigitalEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HiImpedanceDigitalInpDisEMF {
            get {
                object obj = ResourceManager.GetObject("HiImpedanceDigitalInpDisEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Swap.
        /// </summary>
        internal static string HotSwaps {
            get {
                return ResourceManager.GetString("HotSwaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Indeterminate&gt;.
        /// </summary>
        internal static string Indeterminate {
            get {
                return ResourceManager.GetString("Indeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index out of range.
        /// </summary>
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LVTTL.
        /// </summary>
        internal static string LVTTL {
            get {
                return ResourceManager.GetString("LVTTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Frequency.
        /// </summary>
        internal static string MaxFrequency {
            get {
                return ResourceManager.GetString("MaxFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveDownImage {
            get {
                object obj = ResourceManager.GetObject("MoveDownImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveUpImage {
            get {
                object obj = ResourceManager.GetObject("MoveUpImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Pin/s cannot be performed. Cannot have less than one pin remaining..
        /// </summary>
        internal static string Msg_CannotDeleteSelectedPin {
            get {
                return ResourceManager.GetString("Msg_CannotDeleteSelectedPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair SIOs cannot be performed. SIOs can only be paired if they are adjacent to each other and not already in a pair..
        /// </summary>
        internal static string Msg_CannotPairSIOs {
            get {
                return ResourceManager.GetString("Msg_CannotPairSIOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (empty).
        /// </summary>
        internal static string Msg_Empty {
            get {
                return ResourceManager.GetString("Msg_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of pins.
        /// </summary>
        internal static string Msg_InvalidNumberOfPins {
            get {
                return ResourceManager.GetString("Msg_InvalidNumberOfPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid supply voltage.
        /// </summary>
        internal static string Msg_InvalidSupplyVoltage {
            get {
                return ResourceManager.GetString("Msg_InvalidSupplyVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid supply voltage. Value must be numeric and non-negative..
        /// </summary>
        internal static string Msg_InvalidSupplyVoltage_numeric {
            get {
                return ResourceManager.GetString("Msg_InvalidSupplyVoltage_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether to display individual terminals for each pin or a single wide terminal (bus).
        ///The bus option is only valid when pins are homogeneous, which means
        ///     all pins in the component have:
        ///     	- the same pin type,
        ///     	- the same output/input HW connections,
        ///     	- the same SIO grouping,
        /// AND 	- they all either use or don&apos;t use the SIO Vref..
        /// </summary>
        internal static string Msg_MustBeHomogenous {
            get {
                return ResourceManager.GetString("Msg_MustBeHomogenous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the selected pins has its PinType configured to use input settings..
        /// </summary>
        internal static string NoSelectedPinConfigured_input {
            get {
                return ResourceManager.GetString("NoSelectedPinConfigured_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the selected pins has its PinType configured to use output settings..
        /// </summary>
        internal static string NoSelectedPinConfigured_output {
            get {
                return ResourceManager.GetString("NoSelectedPinConfigured_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Drain, Drives High.
        /// </summary>
        internal static string OpenDrainDrivesHigh {
            get {
                return ResourceManager.GetString("OpenDrainDrivesHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OpenDrainDrivesHighEMF {
            get {
                object obj = ResourceManager.GetObject("OpenDrainDrivesHighEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OpenDrainDrivesHighInpDisEMF {
            get {
                object obj = ResourceManager.GetObject("OpenDrainDrivesHighInpDisEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Drain, Drives Low.
        /// </summary>
        internal static string OpenDrainDrivesLow {
            get {
                return ResourceManager.GetString("OpenDrainDrivesLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OpenDrainDrivesLowEMF {
            get {
                object obj = ResourceManager.GetObject("OpenDrainDrivesLowEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OpenDrainDrivesLowInpDisEMF {
            get {
                object obj = ResourceManager.GetObject("OpenDrainDrivesLowInpDisEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or .
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Current.
        /// </summary>
        internal static string OutputCurrentCaps {
            get {
                return ResourceManager.GetString("OutputCurrentCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Drive Level.
        /// </summary>
        internal static string OutputDriveLevels {
            get {
                return ResourceManager.GetString("OutputDriveLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PairSIOsImage {
            get {
                object obj = ResourceManager.GetObject("PairSIOsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PinAliasImage {
            get {
                object obj = ResourceManager.GetObject("PinAliasImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PinImage {
            get {
                object obj = ResourceManager.GetObject("PinImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pins.
        /// </summary>
        internal static string Pins {
            get {
                return ResourceManager.GetString("Pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change alias [{0}].
        /// </summary>
        internal static string Prompt_ChangeAlias {
            get {
                return ResourceManager.GetString("Prompt_ChangeAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}bps.
        /// </summary>
        internal static string Prompt_Mbps {
            get {
                return ResourceManager.GetString("Prompt_Mbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MHz.
        /// </summary>
        internal static string Prompt_MHz {
            get {
                return ResourceManager.GetString("Prompt_MHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pins:.
        /// </summary>
        internal static string Prompt_NumberOfPins {
            get {
                return ResourceManager.GetString("Prompt_NumberOfPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}mA source, {0}mA sink.
        /// </summary>
        internal static string Prompt_SourceSink {
            get {
                return ResourceManager.GetString("Prompt_SourceSink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        internal static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistive Pull Down.
        /// </summary>
        internal static string ResPullDown {
            get {
                return ResourceManager.GetString("ResPullDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ResPullDownEMF {
            get {
                object obj = ResourceManager.GetObject("ResPullDownEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ResPullDownInpDisEMF {
            get {
                object obj = ResourceManager.GetObject("ResPullDownInpDisEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistive Pull Up.
        /// </summary>
        internal static string ResPullUp {
            get {
                return ResourceManager.GetString("ResPullUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistive Pull Up/Down.
        /// </summary>
        internal static string ResPullUpDown {
            get {
                return ResourceManager.GetString("ResPullUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ResPullUpDownEMF {
            get {
                object obj = ResourceManager.GetObject("ResPullUpDownEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ResPullUpDownInpDisEMF {
            get {
                object obj = ResourceManager.GetObject("ResPullUpDownInpDisEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ResPullUpEMF {
            get {
                object obj = ResourceManager.GetObject("ResPullUpEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ResPullUpInpDisEMF {
            get {
                object obj = ResourceManager.GetObject("ResPullUpInpDisEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rising edge.
        /// </summary>
        internal static string RisingEdge {
            get {
                return ResourceManager.GetString("RisingEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIO Pair.
        /// </summary>
        internal static string SIOPair {
            get {
                return ResourceManager.GetString("SIOPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SIOPinImage {
            get {
                object obj = ResourceManager.GetObject("SIOPinImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        internal static string Slow {
            get {
                return ResourceManager.GetString("Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong Drive.
        /// </summary>
        internal static string StrongDrive {
            get {
                return ResourceManager.GetString("StrongDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StrongDriveEMF {
            get {
                object obj = ResourceManager.GetObject("StrongDriveEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StrongDriveInpDisEMF {
            get {
                object obj = ResourceManager.GetObject("StrongDriveInpDisEMF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-Sync.
        /// </summary>
        internal static string SyncMode_DoubleSync {
            get {
                return ResourceManager.GetString("SyncMode_DoubleSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-Sync.
        /// </summary>
        internal static string SyncMode_SingleSync {
            get {
                return ResourceManager.GetString("SyncMode_SingleSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string SyncMode_Transparent {
            get {
                return ResourceManager.GetString("SyncMode_Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Threshold.
        /// </summary>
        internal static string ThresholdLevels {
            get {
                return ResourceManager.GetString("ThresholdLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled drive mode &apos;{0}&apos;..
        /// </summary>
        internal static string UnhandledDriveMode {
            get {
                return ResourceManager.GetString("UnhandledDriveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled pin type &apos;{0}&apos;.
        /// </summary>
        internal static string UnhandledPinType {
            get {
                return ResourceManager.GetString("UnhandledPinType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown terminal name &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownTerm {
            get {
                return ResourceManager.GetString("UnknownTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnpairSIOsImage {
            get {
                object obj = ResourceManager.GetObject("UnpairSIOsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vddio.
        /// </summary>
        internal static string Vddio {
            get {
                return ResourceManager.GetString("Vddio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vref.
        /// </summary>
        internal static string Vref {
            get {
                return ResourceManager.GetString("Vref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vref (internal).
        /// </summary>
        internal static string VrefInternal {
            get {
                return ResourceManager.GetString("VrefInternal", resourceCulture);
            }
        }
    }
}
