//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I2C_LCD_v1_20 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I2C_LCD_v1_20.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API name is already used..
        /// </summary>
        internal static string APINameDuplicate {
            get {
                return ResourceManager.GetString("APINameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API name cannot be in uppercase..
        /// </summary>
        internal static string APINameInUppercase {
            get {
                return ResourceManager.GetString("APINameInUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal API name..
        /// </summary>
        internal static string ApiNameInvalid {
            get {
                return ResourceManager.GetString("ApiNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API name {0} is reserved..
        /// </summary>
        internal static string APINameReserved {
            get {
                return ResourceManager.GetString("APINameReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        internal static string BuiltInTabDisplayName {
            get {
                return ResourceManager.GetString("BuiltInTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set display for 2 lines and 16 characters.
        /// </summary>
        internal static string CmdDesc2Lines16Characters {
            get {
                return ResourceManager.GetString("CmdDesc2Lines16Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move cursor/shift display right (cursor position auto decrement).
        /// </summary>
        internal static string CmdDescAutoDecrement {
            get {
                return ResourceManager.GetString("CmdDescAutoDecrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear screen.
        /// </summary>
        internal static string CmdDescClearScreen {
            get {
                return ResourceManager.GetString("CmdDescClearScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move cursor/shift display right (cursor position auto increment).
        /// </summary>
        internal static string CmdDescCursorAutoIncrement {
            get {
                return ResourceManager.GetString("CmdDescCursorAutoIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display - on, cursor - off, set cursor blink.
        /// </summary>
        internal static string CmdDescCursorBlink {
            get {
                return ResourceManager.GetString("CmdDescCursorBlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor home.
        /// </summary>
        internal static string CmdDescCursorHome {
            get {
                return ResourceManager.GetString("CmdDescCursorHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move cursor left one place.
        /// </summary>
        internal static string CmdDescCursorLeftOnePlace {
            get {
                return ResourceManager.GetString("CmdDescCursorLeftOnePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move cursor right one place.
        /// </summary>
        internal static string CmdDescCursorRightOnePlace {
            get {
                return ResourceManager.GetString("CmdDescCursorRightOnePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display - on, cursor - off, set cursor wink.
        /// </summary>
        internal static string CmdDescCursorWink {
            get {
                return ResourceManager.GetString("CmdDescCursorWink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display and cursor off.
        /// </summary>
        internal static string CmdDescDisplayOff {
            get {
                return ResourceManager.GetString("CmdDescDisplayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display on, cursor off.
        /// </summary>
        internal static string CmdDescDisplayOn {
            get {
                return ResourceManager.GetString("CmdDescDisplayOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load custom character.
        /// </summary>
        internal static string CmdDescLoadCustomCharacter {
            get {
                return ResourceManager.GetString("CmdDescLoadCustomCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset cursor position.
        /// </summary>
        internal static string CmdDescResetCursorPosition {
            get {
                return ResourceManager.GetString("CmdDescResetCursorPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set cursor position.
        /// </summary>
        internal static string CmdDescSetCursorPosition {
            get {
                return ResourceManager.GetString("CmdDescSetCursorPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline cursor on.
        /// </summary>
        internal static string CmdDescUnderlineCursorOn {
            get {
                return ResourceManager.GetString("CmdDescUnderlineCursorOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command pattern for writing data.
        /// </summary>
        internal static string CmdDescWritingDataPattern {
            get {
                return ResourceManager.GetString("CmdDescWritingDataPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I2C LCD.
        /// </summary>
        internal static string ComponentName {
            get {
                return ResourceManager.GetString("ComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ContextMenuDeleteItem {
            get {
                return ResourceManager.GetString("ContextMenuDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Commands.
        /// </summary>
        internal static string CustomCmdTabDisplayName {
            get {
                return ResourceManager.GetString("CustomCmdTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom commands table contains invalid data..
        /// </summary>
        internal static string CustomCommandsDataGridContainsError {
            get {
                return ResourceManager.GetString("CustomCommandsDataGridContainsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default I2C address must be between {0} and {1}..
        /// </summary>
        internal static string DefaultI2cAddressOutOfRange {
            get {
                return ResourceManager.GetString("DefaultI2cAddressOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting row(s). Are you sure?.
        /// </summary>
        internal static string DeletePrompt {
            get {
                return ResourceManager.GetString("DeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom commands table contains empty cells..
        /// </summary>
        internal static string DrcCustomNullValues {
            get {
                return ResourceManager.GetString("DrcCustomNullValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required commands table contains empty cells..
        /// </summary>
        internal static string DrcRequiredNullValues {
            get {
                return ResourceManager.GetString("DrcRequiredNullValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralTabDisplayName {
            get {
                return ResourceManager.GetString("GeneralTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Import {
            get {
                object obj = ResourceManager.GetObject("Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal instance name..
        /// </summary>
        internal static string InstanceNameInvalid {
            get {
                return ResourceManager.GetString("InstanceNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interconnect.
        /// </summary>
        internal static string InterconnectTabDisplayName {
            get {
                return ResourceManager.GetString("InterconnectTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required commands table contains invalid data..
        /// </summary>
        internal static string RequiredCommandsDataGridContainsError {
            get {
                return ResourceManager.GetString("RequiredCommandsDataGridContainsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Format.
        /// </summary>
        internal static string SBCommandFormatCustom {
            get {
                return ResourceManager.GetString("SBCommandFormatCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NXP PCF2119x + Custom Commands.
        /// </summary>
        internal static string SBCommandFormatNXP {
            get {
                return ResourceManager.GetString("SBCommandFormatNXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Char Set - {0}, {1}.
        /// </summary>
        internal static string SBComponentBodyText {
            get {
                return ResourceManager.GetString("SBComponentBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I2C LCD.
        /// </summary>
        internal static string SBComponentTitle {
            get {
                return ResourceManager.GetString("SBComponentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Bar Graph.
        /// </summary>
        internal static string SBCustomCharacterSetLabelHorizontalBarGraph {
            get {
                return ResourceManager.GetString("SBCustomCharacterSetLabelHorizontalBarGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SBCustomCharacterSetLabelNone {
            get {
                return ResourceManager.GetString("SBCustomCharacterSetLabelNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string SBCustomCharacterSetLabelUnknown {
            get {
                return ResourceManager.GetString("SBCustomCharacterSetLabelUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined.
        /// </summary>
        internal static string SBCustomCharacterSetLabelUserDefined {
            get {
                return ResourceManager.GetString("SBCustomCharacterSetLabelUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Bar Graph.
        /// </summary>
        internal static string SBCustomCharacterSetLabelVerticalBarGraph {
            get {
                return ResourceManager.GetString("SBCustomCharacterSetLabelVerticalBarGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have incorrect values! You must redefine them..
        /// </summary>
        internal static string SettingsIncorrectValues {
            get {
                return ResourceManager.GetString("SettingsIncorrectValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between {0} and {1}..
        /// </summary>
        internal static string ValueOutOfRange {
            get {
                return ResourceManager.GetString("ValueOutOfRange", resourceCulture);
            }
        }
    }
}
