/*******************************************************************************
* File Name: `$INSTANCE_NAME`.c
* Version `$CY_MAJOR_VERSION`.`$CY_MINOR_VERSION`
*
* Description:
*  This file provides the source code to the API for the Sequencing Successive
*  Approximation ADC Component Component.
*
* Note:
*
********************************************************************************
* Copyright 2008-2015, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#include "`$INSTANCE_NAME`.h"


/***************************************
* Global data allocation
***************************************/
uint8 `$INSTANCE_NAME`_initVar = 0u;
volatile int16 `$INSTANCE_NAME`_offset[`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM];
volatile int32 `$INSTANCE_NAME`_countsPer10Volt[`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM];   /* Gain compensation */


/***************************************
* Local data allocation
***************************************/
/* Channels configuration generated by customiser */
static `$channelsConfig`


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_Start
********************************************************************************
*
* Summary:
*  Performs all required initialization for this component
*  and enables the power. The power will be set to the appropriate
*  power based on the clock frequency.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
* Global variables:
*  The `$INSTANCE_NAME`_initVar variable is used to indicate when/if initial
*  configuration of this component has happened. The variable is initialized to
*  zero and set to 1 the first time ADC_Start() is called. This allows for
*  component Re-Start without re-initialization in all subsequent calls to the
*  `$INSTANCE_NAME`_Start() routine.
*  If re-initialization of the component is required the variable should be set
*  to zero before call of `$INSTANCE_NAME`_Start() routine, or the user may call
*  `$INSTANCE_NAME`_Init() and `$INSTANCE_NAME`_Enable() as done in the
*  `$INSTANCE_NAME`_Start() routine.
*
*******************************************************************************/
void `$INSTANCE_NAME`_Start(void)
{
    /* If not Initialized then initialize all required hardware and software */
    if(`$INSTANCE_NAME`_initVar == 0u)
    {
        `$INSTANCE_NAME`_Init();
        `$INSTANCE_NAME`_initVar = 1u;
    }
    `$INSTANCE_NAME`_Enable();
}


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_Init
********************************************************************************
*
* Summary:
*  Initialize component's parameters to the parameters set by user in the
*  customizer of the component placed onto schematic. Usually called in
*  `$INSTANCE_NAME`_Start().
*
* Parameters:
*  None.
*
* Return:
*  None.
*
* Global variables:
*  The `$INSTANCE_NAME`_offset variable is initialized.
*
*******************************************************************************/
void `$INSTANCE_NAME`_Init(void)
{
    uint32 chNum;
    uint32 tmpRegVal;
    int32 counts;

    #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 1u)
        static const uint8 CYCODE `$INSTANCE_NAME`_InputsPlacement[] =
        {
            (uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_0_PORT << 4u) |
            (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_0_PIN
            ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_1_PORT << 4u) |
             (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_1_PIN
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 2u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_2_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_2_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 2u */
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 3u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_3_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_3_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 3u */
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 4u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_4_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_4_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 4u */
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 5u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_5_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_5_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 5u */
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 6u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_6_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_6_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 6u */
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 7u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_7_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_7_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 7u */
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 8u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_8_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_8_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 8u */
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 9u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_9_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_9_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 9u */
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 10u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_10_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_10_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 10u */
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 11u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_11_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_11_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 11u */
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 12u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_12_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_12_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 12u */
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 13u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_13_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_13_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 13u */
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 14u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_14_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_14_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 14u */
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 15u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_15_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_15_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 15u */
            #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 16u)
                ,(uint8)(`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_16_PORT << 4u) |
                 (uint8)`$INSTANCE_NAME`_cy_psoc4_sarmux_8__CH_16_PIN
            #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 16u */
        };
    #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 1u */

    #if(`$INSTANCE_NAME`_IRQ_REMOVE == 0u)
        /* Start and set interrupt vector */
        CyIntSetPriority(`$INSTANCE_NAME`_INTC_NUMBER, `$INSTANCE_NAME`_INTC_PRIOR_NUMBER);
        (void)CyIntSetVector(`$INSTANCE_NAME`_INTC_NUMBER, &`$INSTANCE_NAME`_ISR);
    #endif   /* End `$INSTANCE_NAME`_IRQ_REMOVE */

    /* Init SAR and MUX registers */
    `$INSTANCE_NAME`_SAR_CHAN_EN_REG = `$INSTANCE_NAME`_DEFAULT_EN_CHANNELS;
    `$INSTANCE_NAME`_SAR_CTRL_REG |= `$INSTANCE_NAME`_DEFAULT_CTRL_REG_CFG | 
        /* Enable the SAR internal pump when global pump is enabled */
        (((`$INSTANCE_NAME`_PUMP_CTRL_REG & `$INSTANCE_NAME`_PUMP_CTRL_ENABLED) != 0u) ? 
        `$INSTANCE_NAME`_BOOSTPUMP_EN : 0u);
    `$INSTANCE_NAME`_SAR_SAMPLE_CTRL_REG = `$INSTANCE_NAME`_DEFAULT_SAMPLE_CTRL_REG_CFG;
    `$INSTANCE_NAME`_SAR_RANGE_THRES_REG = `$INSTANCE_NAME`_DEFAULT_RANGE_THRES_REG_CFG;
    `$INSTANCE_NAME`_SAR_RANGE_COND_REG  = `$INSTANCE_NAME`_COMPARE_MODE;
    `$INSTANCE_NAME`_SAR_SAMPLE_TIME01_REG = `$INSTANCE_NAME`_DEFAULT_SAMPLE_TIME01_REG_CFG;
    `$INSTANCE_NAME`_SAR_SAMPLE_TIME23_REG = `$INSTANCE_NAME`_DEFAULT_SAMPLE_TIME23_REG_CFG;
    
    /* Connect Vm to VSSA when even one channel is single-ended or multiple channels configured */
    #if(`$INSTANCE_NAME`_DEFAULT_MUX_SWITCH0 != 0u)
        `$INSTANCE_NAME`_MUX_SWITCH0_REG |= `$INSTANCE_NAME`_DEFAULT_MUX_SWITCH0;
        /* Set MUX_HW_CTRL_VSSA in MUX_SWITCH_HW_CTRL when multiple channels enabled */
        #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 1u)
            `$INSTANCE_NAME`_MUX_SWITCH_HW_CTRL_REG |= `$INSTANCE_NAME`_DEFAULT_MUX_SWITCH0;
        #endif /* `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 1u */
    #endif /*`$INSTANCE_NAME`_CHANNELS_MODE !=0 */

    `$INSTANCE_NAME`_SAR_SATURATE_INTR_MASK_REG = 0u;
    `$INSTANCE_NAME`_SAR_RANGE_INTR_MASK_REG = 0u;
    `$INSTANCE_NAME`_SAR_INTR_MASK_REG = `$INSTANCE_NAME`_SAR_INTR_MASK;

    #if(`$INSTANCE_NAME`_CY_SAR_IP_VER == `$INSTANCE_NAME`_CY_SAR_IP_VER0)
        `$INSTANCE_NAME`_ANA_TRIM_REG = `$INSTANCE_NAME`_TRIM_COEF;
    #endif /* (`$INSTANCE_NAME`_CY_SAR_IP_VER == `$INSTANCE_NAME`_CY_SAR_IP_VER0) */

    /* Read and modify default configuration based on characterization */
    tmpRegVal = `$INSTANCE_NAME`_SAR_DFT_CTRL_REG;
    tmpRegVal &= (uint32)~`$INSTANCE_NAME`_DCEN;
    
    #if(`$INSTANCE_NAME`_CY_SAR_IP_VER == `$INSTANCE_NAME`_CY_SAR_IP_VER0)
        #if(`$INSTANCE_NAME`_NOMINAL_CLOCK_FREQ > (`$INSTANCE_NAME`_MAX_FREQUENCY / 2))
            tmpRegVal |= `$INSTANCE_NAME`_SEL_CSEL_DFT_CHAR;
        #else  /* clock speed < 9 Mhz */
            tmpRegVal |= `$INSTANCE_NAME`_DLY_INC;
        #endif /* clock speed > 9 Mhz */
    #else
        #if ((`$INSTANCE_NAME`_DEFAULT_VREF_SEL == `$INSTANCE_NAME`__INTERNAL1024) || \
             (`$INSTANCE_NAME`_DEFAULT_VREF_SEL == `$INSTANCE_NAME`__INTERNALVREF))
            tmpRegVal |= `$INSTANCE_NAME`_DLY_INC;
        #else
            tmpRegVal |= `$INSTANCE_NAME`_DCEN;
            tmpRegVal &= (uint32)~`$INSTANCE_NAME`_DLY_INC;
        #endif /* ((`$INSTANCE_NAME`_DEFAULT_VREF_SEL == `$INSTANCE_NAME`__INTERNAL1024) || \
                   (`$INSTANCE_NAME`_DEFAULT_VREF_SEL == `$INSTANCE_NAME`__INTERNALVREF)) */
    #endif /* (`$INSTANCE_NAME`_CY_SAR_IP_VER == `$INSTANCE_NAME`_CY_SAR_IP_VER0) */
    
    `$INSTANCE_NAME`_SAR_DFT_CTRL_REG = tmpRegVal;

    #if(`$INSTANCE_NAME`_MAX_RESOLUTION != `$INSTANCE_NAME`_RESOLUTION_12)
        `$INSTANCE_NAME`_WOUNDING_REG = `$INSTANCE_NAME`_ALT_WOUNDING;
    #endif /* `$INSTANCE_NAME`_MAX_RESOLUTION != `$INSTANCE_NAME`_RESOLUTION_12 */

    for(chNum = 0u; chNum < `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM; chNum++)
    {
        tmpRegVal = (`$INSTANCE_NAME`_channelsConfig[chNum] & `$INSTANCE_NAME`_CHANNEL_CONFIG_MASK);
        #if(`$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 1u)
            tmpRegVal |= `$INSTANCE_NAME`_InputsPlacement[chNum];
        #endif /* End `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM > 1u */
        
        
        /* When the part is limited to 10-bit then the SUB_RESOLUTION bit
        *  will be ignored and the RESOLUTION bit selects between 10-bit
        *  (0) and 8-bit (1) resolution.
        */
        #if((`$INSTANCE_NAME`_MAX_RESOLUTION != `$INSTANCE_NAME`_RESOLUTION_12) && \
            (`$INSTANCE_NAME`_ALT_WOUNDING == `$INSTANCE_NAME`_WOUNDING_10BIT))
            tmpRegVal &= (uint32)(~`$INSTANCE_NAME`_ALT_RESOLUTION_ON);
        #endif /* `$INSTANCE_NAME`_MAX_RESOLUTION != `$INSTANCE_NAME`_RESOLUTION_12 */

        #if(`$INSTANCE_NAME`_INJ_CHANNEL_ENABLED)
        if(chNum < `$INSTANCE_NAME`_SEQUENCED_CHANNELS_NUM)
        #endif /* `$INSTANCE_NAME`_INJ_CHANNEL_ENABLED */
        {
            CY_SET_REG32((reg32 *)(`$INSTANCE_NAME`_SAR_CHAN_CONFIG_IND + (uint32)(chNum << 2)), tmpRegVal);

            if((`$INSTANCE_NAME`_channelsConfig[chNum] & `$INSTANCE_NAME`_IS_SATURATE_EN_MASK) != 0u)
            {
                `$INSTANCE_NAME`_SAR_SATURATE_INTR_MASK_REG |= (uint16)((uint16)1 << chNum);
            }

            if((`$INSTANCE_NAME`_channelsConfig[chNum] & `$INSTANCE_NAME`_IS_RANGE_CTRL_EN_MASK) != 0u)
            {
                `$INSTANCE_NAME`_SAR_RANGE_INTR_MASK_REG |= (uint16)((uint16)1 << chNum);
            }
        }
        #if(`$INSTANCE_NAME`_INJ_CHANNEL_ENABLED)
            else
            {
                CY_SET_REG32(`$INSTANCE_NAME`_SAR_INJ_CHAN_CONFIG_PTR, tmpRegVal | `$INSTANCE_NAME`_INJ_TAILGATING);

                if((`$INSTANCE_NAME`_channelsConfig[chNum] & `$INSTANCE_NAME`_IS_SATURATE_EN_MASK) != 0u)
                {
                    `$INSTANCE_NAME`_SAR_INTR_MASK_REG |= `$INSTANCE_NAME`_INJ_SATURATE_MASK;
                }

                if((`$INSTANCE_NAME`_channelsConfig[chNum] & `$INSTANCE_NAME`_IS_RANGE_CTRL_EN_MASK) != 0u)
                {
                    `$INSTANCE_NAME`_SAR_INTR_MASK_REG |= `$INSTANCE_NAME`_INJ_RANGE_MASK;
                }
            }
        #endif /* `$INSTANCE_NAME`_INJ_CHANNEL_ENABLED */

        if((`$INSTANCE_NAME`_channelsConfig[chNum] & `$INSTANCE_NAME`_ALT_RESOLUTION_ON) != 0u)
        {
               counts = (int32)`$INSTANCE_NAME`_DEFAULT_MAX_WRK_ALT;
        }
        else
        {
               counts = (int32)`$INSTANCE_NAME`_SAR_WRK_MAX_12BIT;
        }

        if((`$INSTANCE_NAME`_channelsConfig[chNum] & `$INSTANCE_NAME`_DIFFERENTIAL_EN) == 0u)
        {
            #if((`$INSTANCE_NAME`_DEFAULT_SE_RESULT_FORMAT_SEL == `$INSTANCE_NAME`__FSIGNED) && \
                (`$INSTANCE_NAME`_DEFAULT_NEG_INPUT_SEL == `$INSTANCE_NAME`__VREF))
                /* Set offset to the minus half scale to convert results to unsigned format */
                `$INSTANCE_NAME`_offset[chNum] = (int16)(counts / -2);
            #else
                `$INSTANCE_NAME`_offset[chNum] = 0;
            #endif /* end DEFAULT_SE_RESULT_FORMAT_SEL == `$INSTANCE_NAME`__FSIGNED */
        }
        else    /* Differential channel */
        {
            #if(`$INSTANCE_NAME`_DEFAULT_DIFF_RESULT_FORMAT_SEL == `$INSTANCE_NAME`__FUNSIGNED)
                /* Set offset to the half scale to convert results to signed format */
                `$INSTANCE_NAME`_offset[chNum] = (int16)(counts / 2);
            #else
                `$INSTANCE_NAME`_offset[chNum] = 0;
            #endif /* end `$INSTANCE_NAME`_DEFAULT_DIFF_RESULT_FORMAT_SEL == `$INSTANCE_NAME`__FUNSIGNED */
        }
        /* Calculate gain in counts per 10 volts with rounding */
        `$INSTANCE_NAME`_countsPer10Volt[chNum] = (int16)(((counts * `$INSTANCE_NAME`_10MV_COUNTS) +
                            `$INSTANCE_NAME`_DEFAULT_VREF_MV_VALUE) / (`$INSTANCE_NAME`_DEFAULT_VREF_MV_VALUE * 2));
    }
}

/*******************************************************************************
* Function Name: ADC_SAR_1_Enable
********************************************************************************
*
* Summary:
*  Enables the clock and analog power for SAR ADC.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void `$INSTANCE_NAME`_Enable(void)
{
    if (0u == (`$INSTANCE_NAME`_SAR_CTRL_REG & `$INSTANCE_NAME`_ENABLE))
    {
        #if(`$INSTANCE_NAME`_CY_SAR_IP_VER != `$INSTANCE_NAME`_CY_SAR_IP_VER0)

            while (0u != (`$INSTANCE_NAME`_SAR_STATUS_REG & `$INSTANCE_NAME`_STATUS_BUSY))
            {
                /* wait for SAR to go idle to avoid deadlock */
            }
        #endif /* (`$INSTANCE_NAME`_CY_SAR_IP_VER != `$INSTANCE_NAME`_CY_SAR_IP_VER0) */
        
        `$INSTANCE_NAME`_SAR_CTRL_REG |= `$INSTANCE_NAME`_ENABLE;
        
        /* The block is ready to use 10 us after the enable signal is set high. */
        CyDelayUs(`$INSTANCE_NAME`_10US_DELAY);         
    }
}


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_Stop
********************************************************************************
*
* Summary:
*  This function stops ADC conversions and puts the ADC into its lowest power
*  mode.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void `$INSTANCE_NAME`_Stop(void)
{
    `$INSTANCE_NAME`_SAR_CTRL_REG &= (uint32)~`$INSTANCE_NAME`_ENABLE;
}


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_StartConvert
********************************************************************************
*
* Summary:
*  Description:
*  For free running mode, this API starts the conversion process and it
*  runs continuously.
*
*  In a triggered mode, this routine triggers every conversion by
*  writing into the FW_TRIGGER bit in SAR_START_CTRL reg. In triggered mode,
*  every conversion has to start by this API.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void `$INSTANCE_NAME`_StartConvert(void)
{
    #if(`$INSTANCE_NAME`_DEFAULT_SAMPLE_MODE_SEL == `$INSTANCE_NAME`__FREERUNNING)
        `$INSTANCE_NAME`_SAR_SAMPLE_CTRL_REG |= `$INSTANCE_NAME`_CONTINUOUS_EN;
    #else /* Firmware trigger */
        `$INSTANCE_NAME`_SAR_START_CTRL_REG = `$INSTANCE_NAME`_FW_TRIGGER;
    #endif /* End `$INSTANCE_NAME`_DEFAULT_SAMPLE_MODE == `$INSTANCE_NAME`__FREERUNNING */

}


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_StopConvert
********************************************************************************
*
* Summary:
*  Forces the ADC to stop all conversions.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void `$INSTANCE_NAME`_StopConvert(void)
{
    #if(`$INSTANCE_NAME`_DEFAULT_SAMPLE_MODE_SEL == `$INSTANCE_NAME`__FREERUNNING)
        `$INSTANCE_NAME`_SAR_SAMPLE_CTRL_REG &= (uint32)(~`$INSTANCE_NAME`_CONTINUOUS_EN);
    #endif /* `$INSTANCE_NAME`_DEFAULT_SAMPLE_MODE == `$INSTANCE_NAME`__FREERUNNING */
}


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_IsEndConversion
********************************************************************************
*
* Summary:
*  Description: Checks for ADC end of conversion for the case one
*  channel and end of scan for the case of multiple channels. It acts
*  as a software version of the EOC. This function provides the
*  programmer with two options. In one mode this function
*  immediately returns with the conversion status. In the other mode,
*  the function does not return (blocking) until the conversion has
*  completed.
*
* Parameters:
*  ADC_RETURN_STATUS        -> Immediately returns conversion result status
*  ADC_WAIT_FOR_RESULT      -> Does not return until ADC complete
*  ADC_RETURN_STATUS_INJ    -> Immediately returns conversion result status
*                              for injection channel
*  ADC_WAIT_FOR_RESULT_INJ  -> Does not return until ADC completes injection
*                              channel conversion
*
* Return:
*  If a non-zero value is returned, the last conversion or scan has completed.
*  If the returned value is zero, the ADC is still in the process of a scan.
*
*******************************************************************************/
uint32 `$INSTANCE_NAME`_IsEndConversion(uint32 retMode)
{
    uint32 status = 0u;

    if((retMode & (`$INSTANCE_NAME`_RETURN_STATUS | `$INSTANCE_NAME`_WAIT_FOR_RESULT)) != 0u)
    {
        do
        {
            status = `$INSTANCE_NAME`_SAR_INTR_REG & `$INSTANCE_NAME`_EOS_MASK;
        }while((status == 0u) && ((retMode & `$INSTANCE_NAME`_WAIT_FOR_RESULT) != 0u));

        if(status != 0u)
        {
            /* Clear EOS bit */
            `$INSTANCE_NAME`_SAR_INTR_REG = `$INSTANCE_NAME`_EOS_MASK;
        }
    }

    #if(`$INSTANCE_NAME`_INJ_CHANNEL_ENABLED)
        if((retMode & (`$INSTANCE_NAME`_RETURN_STATUS_INJ | `$INSTANCE_NAME`_WAIT_FOR_RESULT_INJ)) != 0u)
        {
            do
            {
                status |= `$INSTANCE_NAME`_SAR_INTR_REG & `$INSTANCE_NAME`_INJ_EOC_MASK;
            }while(((status & `$INSTANCE_NAME`_INJ_EOC_MASK) == 0u) &&
                   ((retMode & `$INSTANCE_NAME`_WAIT_FOR_RESULT_INJ) != 0u));

            if((status & `$INSTANCE_NAME`_INJ_EOC_MASK) != 0u)
            {
                /* Clear Injection EOS bit */
                `$INSTANCE_NAME`_SAR_INTR_REG = `$INSTANCE_NAME`_INJ_EOC_MASK;
            }
        }
    #endif /* `$INSTANCE_NAME`_INJ_CHANNEL_ENABLED */

    return (status);
}


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_GetResult16
********************************************************************************
*
* Summary:
*  Gets the data available in the SAR DATA register.
*
* Parameters:
*  chan: The ADC channel in which to return the result. The first channel
*  is 0 and the injection channel if enabled is the number of valid channels.
*
* Return:
*  Returns converted data as a signed 16-bit integer
*
*******************************************************************************/
int16 `$INSTANCE_NAME`_GetResult16(uint32 chan)
{
    uint32 result;

    /* Halt CPU in debug mode if channel is out of valid range */
    CYASSERT(chan < `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM);

    if(chan < `$INSTANCE_NAME`_SEQUENCED_CHANNELS_NUM)
    {
        result = CY_GET_REG32((reg32 *)(`$INSTANCE_NAME`_SAR_CHAN_RESULT_IND + (uint32)(chan << 2u))) &
                `$INSTANCE_NAME`_RESULT_MASK;
    }
    else
    {
        #if(`$INSTANCE_NAME`_INJ_CHANNEL_ENABLED)
            result = `$INSTANCE_NAME`_SAR_INJ_RESULT_REG & `$INSTANCE_NAME`_RESULT_MASK;
        #else
            result = 0u;
        #endif /* `$INSTANCE_NAME`_INJ_CHANNEL_ENABLED */
    }

    return ( (int16)result );
}


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_SetChanMask
********************************************************************************
*
* Summary:
*  Sets the channel enable mask.
*
* Parameters:
*  mask: Sets which channels that will be
*  scanned. Setting bits for channels that do not exist will have no
*  effect. For example, if only 6 channels were enabled, setting a
*  mask of 0x0103 would only enable the last two channels (0 and 1).
*  This API will not enable the injection channel.
*  Examples: If the component is setup to sequence through 8
*  channels, a mask of 0x000F would enable channels 0, 1, 2, and 3.
*
* Return:
*  None.
*
*******************************************************************************/
void `$INSTANCE_NAME`_SetChanMask(uint32 mask)
{
    `$INSTANCE_NAME`_SAR_CHAN_EN_REG = mask & `$INSTANCE_NAME`_MAX_CHANNELS_EN_MASK;
}

#if(`$INSTANCE_NAME`_INJ_CHANNEL_ENABLED)


    /*******************************************************************************
    * Function Name: `$INSTANCE_NAME`_EnableInjection
    ********************************************************************************
    *
    * Summary:
    *  Enables the injection channel for the next scan only.
    *
    * Parameters:
    *  None.
    *
    * Return:
    *  None.
    *
    *******************************************************************************/
    void `$INSTANCE_NAME`_EnableInjection(void)
    {
        `$INSTANCE_NAME`_SAR_INJ_CHAN_CONFIG_REG |= `$INSTANCE_NAME`_INJ_CHAN_EN;
    }

#endif /* `$INSTANCE_NAME`_INJ_CHANNEL_ENABLED */


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_SetLowLimit
********************************************************************************
*
* Summary:
*  Sets the low limit parameter for a limit condition.
*
* Parameters:
*  lowLimit: The low limit for a limit condition.
*
* Return:
*  None.
*
*******************************************************************************/
void `$INSTANCE_NAME`_SetLowLimit(uint32 lowLimit)
{
    `$INSTANCE_NAME`_SAR_RANGE_THRES_REG &= (uint32)(~`$INSTANCE_NAME`_RANGE_LOW_MASK);
    `$INSTANCE_NAME`_SAR_RANGE_THRES_REG |= lowLimit & `$INSTANCE_NAME`_RANGE_LOW_MASK;
}


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_SetHighLimit
********************************************************************************
*
* Summary:
*  Sets the low limit parameter for a limit condition.
*
* Parameters:
*  highLimit: The high limit for a limit condition.
*
* Return:
*  None.
*
*******************************************************************************/
void `$INSTANCE_NAME`_SetHighLimit(uint32 highLimit)
{
    `$INSTANCE_NAME`_SAR_RANGE_THRES_REG &= (uint32)(~`$INSTANCE_NAME`_RANGE_HIGH_MASK);
    `$INSTANCE_NAME`_SAR_RANGE_THRES_REG |= (uint32)(highLimit << `$INSTANCE_NAME`_RANGE_HIGH_OFFSET);
}


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_SetLimitMask
********************************************************************************
*
* Summary:
*  Sets the channel limit condition mask.
*
* Parameters:
*  mask: Sets which channels that may cause a
*  limit condition interrupt. Setting bits for channels that do not exist
*  will have no effect. For example, if only 6 channels were enabled,
*  setting a mask of 0x0103 would only enable the last two channels (0 and 1).
*
* Return:
*  None.
*
*******************************************************************************/
void `$INSTANCE_NAME`_SetLimitMask(uint32 mask)
{
    `$INSTANCE_NAME`_SAR_RANGE_INTR_MASK_REG = mask & `$INSTANCE_NAME`_MAX_CHANNELS_EN_MASK;
}


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_SetSatMask
********************************************************************************
*
* Summary:
*  Sets the channel saturation event mask.
*
* Parameters:
*  mask: Sets which channels that may cause a
*  saturation event interrupt. Setting bits for channels that do not exist
*  will have no effect. For example, if only 8 channels were enabled,
*  setting a mask of 0x01C0 would only enable two channels (6 and 7).
*
* Return:
*  None.
*
*******************************************************************************/
void `$INSTANCE_NAME`_SetSatMask(uint32 mask)
{
    `$INSTANCE_NAME`_SAR_SATURATE_INTR_MASK_REG = mask & `$INSTANCE_NAME`_MAX_CHANNELS_EN_MASK;
}


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_SetOffset
********************************************************************************
*
* Summary:
*   Description: Sets the ADC offset which is used by the functions
*   ADC_CountsTo_uVolts, ADC_CountsTo_mVolts and ADC_CountsTo_Volts
*   to substract the offset from the given reading
*   before calculating the voltage conversion.
*
* Parameters:
*  chan: ADC channel number.
*  offset: This value is a measured value when the
*          inputs are shorted or connected to the same input voltage.
*
* Return:
*  None.
*
* Global variables:
*  `$INSTANCE_NAME`_Offset:  Modified to set the user provided offset.
*
*******************************************************************************/
void `$INSTANCE_NAME`_SetOffset(uint32 chan, int16 offset)
{
    /* Halt CPU in debug mode if channel is out of valid range */
    CYASSERT(chan < `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM);

    `$INSTANCE_NAME`_offset[chan] = offset;
}


/*******************************************************************************
* Function Name: `$INSTANCE_NAME`_SetGain
********************************************************************************
*
* Summary:
*  Description: Sets the ADC gain in counts per 10 volt for the voltage
*  conversion functions below. This value is set by default by the
*  reference and input range settings. It should only be used to further
*  calibrate the ADC with a known input or if an external reference is
*  used. Affects the ADC_CountsTo_uVolts, ADC_CountsTo_mVolts
*  and ADC_CountsTo_Volts functions by supplying the correct
*  conversion between ADC counts and voltage.
*
* Parameters:
*  chan: ADC channel number.
*  adcGain: ADC gain in counts per 10 volts.
*
* Return:
*  None.
*
* Global variables:
*  `$INSTANCE_NAME`_CountsPer10Volt:  modified to set the ADC gain in counts
*   per 10 volt.
*
*******************************************************************************/
void `$INSTANCE_NAME`_SetGain(uint32 chan, int32 adcGain)
{
    /* Halt CPU in debug mode if channel is out of valid range */
    CYASSERT(chan < `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM);

    `$INSTANCE_NAME`_countsPer10Volt[chan] = adcGain;
}


#if(`$INSTANCE_NAME`_DEFAULT_JUSTIFICATION_SEL == `$INSTANCE_NAME`__RIGHT)


    /*******************************************************************************
    * Function Name: `$INSTANCE_NAME`_CountsTo_mVolts
    ********************************************************************************
    *
    * Summary:
    *  This function converts ADC counts to mVolts
    *  This function is not available when left data format justification selected.
    *
    * Parameters:
    *  chan: The ADC channel number.
    *  adcCounts: Result from the ADC conversion
    *
    * Return:
    *  Results in mVolts
    *
    * Global variables:
    *  `$INSTANCE_NAME`_countsPer10Volt:  used to convert ADC counts to mVolts.
    *  `$INSTANCE_NAME`_Offset:  Used as the offset while converting ADC counts
    *   to mVolts.
    *
    *******************************************************************************/
    int16 `$INSTANCE_NAME`_CountsTo_mVolts(uint32 chan, int16 adcCounts)
    {
        int16 mVolts;

        /* Halt CPU in debug mode if channel is out of valid range */
        CYASSERT(chan < `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM);

        /* Divide the adcCount when accumulate averaging mode selected */
        #if(`$INSTANCE_NAME`_DEFAULT_AVG_MODE == `$INSTANCE_NAME`__ACCUMULATE)
            if((`$INSTANCE_NAME`_channelsConfig[chan] & `$INSTANCE_NAME`_AVERAGING_EN) != 0u)
            {
                adcCounts /= `$INSTANCE_NAME`_DEFAULT_AVG_SAMPLES_DIV;
            }
        #endif /* `$INSTANCE_NAME`_DEFAULT_AVG_MODE == `$INSTANCE_NAME`__ACCUMULATE */

        /* Subtract ADC offset */
        adcCounts -= `$INSTANCE_NAME`_offset[chan];

        mVolts = (int16)((((int32)adcCounts * `$INSTANCE_NAME`_10MV_COUNTS) + ( (adcCounts > 0) ?
                 (`$INSTANCE_NAME`_countsPer10Volt[chan] / 2) : (-(`$INSTANCE_NAME`_countsPer10Volt[chan] / 2)) ))
                 / `$INSTANCE_NAME`_countsPer10Volt[chan]);

        return( mVolts );
    }


    /*******************************************************************************
    * Function Name: `$INSTANCE_NAME`_CountsTo_uVolts
    ********************************************************************************
    *
    * Summary:
    *  This function converts ADC counts to micro Volts
    *  This function is not available when left data format justification selected.
    *
    * Parameters:
    *  chan: The ADC channel number.
    *  adcCounts: Result from the ADC conversion
    *
    * Return:
    *  Results in uVolts
    *
    * Global variables:
    *  `$INSTANCE_NAME`_countsPer10Volt:  used to convert ADC counts to uVolts.
    *  `$INSTANCE_NAME`_Offset:  Used as the offset while converting ADC counts
    *   to mVolts.
    *
    * Theory:
    *  Care must be taken to not exceed the maximum value for a 31 bit signed
    *  number in the conversion to uVolts and at the same time not loose
    *  resolution.
    *  To convert adcCounts to microVolts it is required to be multiplied
    *  on 10 million and later divide on gain in counts per 10V.
    *
    *******************************************************************************/
    int32 `$INSTANCE_NAME`_CountsTo_uVolts(uint32 chan, int16 adcCounts)
    {
        int64 uVolts;

        /* Halt CPU in debug mode if channel is out of valid range */
        CYASSERT(chan < `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM);

        /* Divide the adcCount when accumulate averaging mode selected */
        #if(`$INSTANCE_NAME`_DEFAULT_AVG_MODE == `$INSTANCE_NAME`__ACCUMULATE)
            if((`$INSTANCE_NAME`_channelsConfig[chan] & `$INSTANCE_NAME`_AVERAGING_EN) != 0u)
            {
                adcCounts /= `$INSTANCE_NAME`_DEFAULT_AVG_SAMPLES_DIV;
            }
        #endif /* `$INSTANCE_NAME`_DEFAULT_AVG_MODE == `$INSTANCE_NAME`__ACCUMULATE */

        /* Subtract ADC offset */
        adcCounts -= `$INSTANCE_NAME`_offset[chan];

        uVolts = ((int64)adcCounts * `$INSTANCE_NAME`_10UV_COUNTS) / `$INSTANCE_NAME`_countsPer10Volt[chan];

        return( (int32)uVolts );
    }


    /*******************************************************************************
    * Function Name: `$INSTANCE_NAME`_CountsTo_Volts
    ********************************************************************************
    *
    * Summary:
    *  Converts the ADC output to Volts as a floating point number.
    *  This function is not available when left data format justification selected.
    *
    * Parameters:
    *  chan: The ADC channel number.
    *  Result from the ADC conversion
    *
    * Return:
    *  Results in Volts
    *
    * Global variables:
    *  `$INSTANCE_NAME`_countsPer10Volt:  used to convert ADC counts to Volts.
    *  `$INSTANCE_NAME`_Offset:  Used as the offset while converting ADC counts
    *   to mVolts.
    *
    *******************************************************************************/
    float32 `$INSTANCE_NAME`_CountsTo_Volts(uint32 chan, int16 adcCounts)
    {
        float32 volts;

        /* Halt CPU in debug mode if channel is out of valid range */
        CYASSERT(chan < `$INSTANCE_NAME`_TOTAL_CHANNELS_NUM);

        /* Divide the adcCount when accumulate averaging mode selected */
        #if(`$INSTANCE_NAME`_DEFAULT_AVG_MODE == `$INSTANCE_NAME`__ACCUMULATE)
            if((`$INSTANCE_NAME`_channelsConfig[chan] & `$INSTANCE_NAME`_AVERAGING_EN) != 0u)
            {
                adcCounts /= `$INSTANCE_NAME`_DEFAULT_AVG_SAMPLES_DIV;
            }
        #endif /* `$INSTANCE_NAME`_DEFAULT_AVG_MODE == `$INSTANCE_NAME`__ACCUMULATE */

        /* Subtract ADC offset */
        adcCounts -= `$INSTANCE_NAME`_offset[chan];

        volts = ((float32)adcCounts * `$INSTANCE_NAME`_10V_COUNTS) / (float32)`$INSTANCE_NAME`_countsPer10Volt[chan];

        return( volts );
    }

#endif /* End `$INSTANCE_NAME`_DEFAULT_JUSTIFICATION_SEL == `$INSTANCE_NAME`__RIGHT */


/* [] END OF FILE */
